<a href="https://colab.research.google.com/github/Shokir-developer/test_numPy_speed/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
sonlar = [1, 6, 8, 9]
n_array = np.array(sonlar)

In [3]:
n_array

array([1, 6, 8, 9])

In [4]:
n_array.ndim

1

In [5]:
n_array.shape

(4,)

In [6]:
n_array.size

4

In [9]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
arr2 = np.arange(3, 20)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
arr3 = np.arange(3, 20, 2)
arr3

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
arr4 = np.zeros((2, 4))
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
arr5 = np.ones((2, 4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
arr6 = np.full((3, 4), 5)
arr6

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [15]:
arr7= np.random.rand(3, 4)
arr7

array([[0.34421656, 0.54014514, 0.94772142, 0.70986588],
       [0.67003971, 0.8452704 , 0.77836275, 0.2619449 ],
       [0.9817891 , 0.36707426, 0.21203904, 0.50205613]])

In [16]:
arr8 = np.random.randint(5, 15, (3, 4))
arr8

array([[13,  6,  6, 10],
       [10, 10,  9, 13],
       [ 9,  9,  5, 14]])

In [17]:
arr9 = np.atleast_1d([1, 2, 3, 4])
arr9

array([1, 2, 3, 4])

In [18]:
arr10 = np.eye(5)
arr10

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr11 = np.identity(10)
arr11

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])